accumulate_grad_batches: 1
amp: false
atom_selection: backbone
backbone: vit
batch_size: 32
ce_re_ratio:
- 1.0
- 1.0
ce_weights:
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
confusion_thresh:
- 306
- 310
data_dir: /Scr/hyunpark/Monster/vaegan_md_gitlab/data
dropout: 0
epoches: 2
filename: dppc.pickle
gpu: false
gradient_clip: null
gudhi: false
ignore_topologicallayer: false
label_smoothing: 0.0
last: 200
learning_rate: 0.001
load_ckpt_path: /Scr/hyunpark-new/Memb-TDA/saved
log: false
loss: hybrid
low_memory: false
maxdim: 1
multiprocessing: false
multiprocessing_backend: ray
name: mpnn
num_workers: 0
optimizer: adam
pdb: null
pdb_database: /Scr/arango/Sobolev-Hyun/2-MembTempredict/testing/
pin_memory: true
preprocessing_only: false
psf: null
resume: false
ripspp: false
save_dir: /Scr/hyunpark-new/Memb-TDA/pickled_indiv/
scheduler: reduce
search_system: ABC
search_temp: 123
shard: false
silent: false
teacher_name: mpnn
tensor: false
train_frac: 0.8
trajs: null
truncated: false
use_artifacts: false
warm_up_split: 5
weight_decay: 2.0e-05
which_mode: preprocessing
which_xai: saliency
