#!/bin/bash

JOBNAME="${1/%.py/}"
LOGNAME="${2}"
MODELNAME="${3}"
MACHINENAME="${4}"

echo "$JOBNAME"
if [ -z "$1" ]; then
  echo "Useage: submit_local PYTHON_FILE_NAME_WITH_DOTPY LOGFILE_NAME MODEL_NAME MACHINENAME"
  exit
fi
if [ ! -f $JOBNAME.py ]; then
	echo "Distributed Python input file $JOBNAME.py does not exist!"
	exit -1
fi

if [ ! -f $JOBNAME.log ]; then
        echo "Distributed Python output file $JOBNAME.log does not exist!"
        touch $JOBNAME.log 
fi	

qsub -q $MACHINENAME -N $JOBNAME -j y -o ~/Jobs << EOF
cd "$PWD"
/Scr/hyunpark/anaconda3/envs/ai/bin/torchrun --nnodes=1 --nproc_per_node=gpu --max_restarts 0 --module main --which_mode train --name convnext_model_indiv_2 --backbone convnext --filename dppc.pickle --multiprocessing --optimizer torch_adam --gpu --epoches 1000 --ce_re_ratio 1 0.1 --load_ckpt_path /Scr/hyunpark-new/Protein-TDA/saved --save_dir /Scr/hyunpark-new/Protein-TDA/pickled_indiv --truncated --batch_size 512 --resume
EOF



